Foreground yes
User clamav
TCPSocket 3310
TCPAddr 0.0.0.0
LocalSocket /tmp/clamd.sock
DatabaseDirectory /var/lib/clamav
LogTime yes
LogFile /tmp/clamd.log
LogFileMaxSize 2M
StreamMaxLength 3M
MaxFileSize 3M
MaxScanSize 20M
MaxRecursion 16
MaxFiles 1000
MaxThreads 2
ScanPDF yes
HeuristicAlerts yes
AlertEncrypted yes
AlertExceedsMax yes
SelfCheck 60
