import type { OrganizationChoice } from './routes';
import type { RequirementResolution } from './requirement-resolution';
export type Organization = OrganizationChoice & {
  legal_name: string;
  slug: string;
  website: string | null;
  status: string;
  default_timezone: string;
  organization_type: string;
};
export type Fact = {
  structured_kind?: string | null;
  structured_fields?: Record<string, string> | null;
  id: string;
  fact_type: string;
  label: string;
  value: string | null;
  verification_status: string;
  source_reference: string | null;
  source_note: string | null;
  verified_by: string | null;
  verified_at: string | null;
  expiration_date: string | null;
  effective_date?: string | null;
  owner_user_id?: string | null;
  sensitivity?: string;
  updated_at: string;
};
export type LiveOpportunity = {
  source_details?: import('./sources/normalized').NormalizedDetails | null;
  updated_at?: string;
  id: string;
  title: string;
  solicitation_number: string | null;
  buyer: string | null;
  source_url: string | null;
  source_note: string | null;
  official_deadline: string | null;
  deadline_timezone: string;
  summary: string | null;
  estimated_value: number | null;
  status: string;
};
export type LivePursuit = {
  updated_at?: string;
  id: string;
  title: string;
  opportunity_id: string;
  decision: string;
  status: string;
};
export type TenantData = {
  evidenceMonitoring?: import('./evidence-monitor').EvidenceMonitoring;
  selfServiceEnabled?: boolean;
  contractorWorkflowEnabled?: boolean;
  amendments?: {
    id: string;
    updated_at: string;
    label: string;
    issued_on: string | null;
    source_url: string;
    summary: string;
    reviewed: boolean;
    reviewed_by: string | null;
    reviewed_at: string | null;
  }[];
  registerSignoffsEnabled?: boolean;
  registerSignoffs?: {
    id: string;
    context_token: string;
    note: string;
    signed_off_by: string;
    signed_off_at: string;
    requirement_count: number;
    blocker_count: number;
    clarification_count: number;
  }[];
  structuredProfilesEnabled?: boolean;
  releaseWorkflow?: import('./response-release').ReleaseWorkspace;
  responsePackages?: import('./response-package').SavedResponsePackage[];
  sourceAttention?: number;
  sourceIssue?: boolean;
  sourceProvenance?: { opportunity_id: string; change_pending: boolean }[];
  documentsEnabled?: boolean;
  documentLibraries?: { id: string; title: string }[];
  documentVersions?: {
    id: string;
    document_id: string;
    version: number;
    sha256: string;
    byte_size: number;
    scan_status: string;
    created_at: string;
  }[];
  documentLinks?: {
    id: string;
    requirement_id: string;
    document_version_id: string;
    source_reference: string;
  }[];
  resolutionsEnabled?: boolean;
  resolutions?: RequirementResolution[];
  resolutionHistory?: RequirementResolution[];
  decisionsEnabled?: boolean;
  decisionContext?: string;
  decisions?: {
    preliminary_state?: string | null;
    reason_codes?: string[];
    estimated_pursuit_hours?: number | null;
    register_signoff_id?: string | null;
    id: string;
    decision: string;
    reason: string;
    conditions: string;
    context_token: string;
    decided_by: string;
    decided_at: string;
  }[];
  evidenceReviewsEnabled?: boolean;
  evidenceReviews?: {
    id: string;
    requirement_id: string;
    fact_id: string;
    applicability: string;
    proposal_use: string;
    approval_current: boolean | null;
    reason: string;
    reviewed_by: string;
    reviewed_at: string;
  }[];
  requirements?: {
    id: string;
    pursuit_id: string;
    requirement: string;
    citation: string | null;
    status: string;
    owner_user_id: string | null;
    updated_at: string;
  }[];
  archivedRequirements?: (NonNullable<TenantData['requirements']>[number] & {
    archived_at: string;
    archived_by: string;
    archive_reason: string;
    merged_into_id: string | null;
  })[];
  requirementLifecycle?: {
    id: string;
    requirement_id: string;
    target_id: string | null;
    action: 'archive' | 'restore' | 'merge';
    reason: string;
    recorded_by: string;
    recorded_at: string;
    before_source: { requirement: string; citation: string | null };
    before_target: { requirement: string; citation: string | null } | null;
  }[];
  reviewAsOf: string;
  organization: Organization;
  choices: OrganizationChoice[];
  userEmail: string;
  userId: string;
  facts: Fact[];
  onboarding: { id: string; label: string; status: string }[];
  sources: { id: string; name: string; access_status: string; notes: string | null }[];
  opportunities: LiveOpportunity[];
  pursuits: LivePursuit[];
  documents: { id: string; title: string; document_type: string; scan_status: string }[];
  members: { id: string; user_id: string; role: string; status: string }[];
  audit: {
    id: string;
    entity_table: string;
    action: string;
    created_at: string;
    actor_user_id: string | null;
  }[];
  tasks: {
    requirement_id?: string | null;
    priority?: string;
    notes?: string;
    completed_at?: string | null;
    created_by?: string | null;
    id: string;
    pursuit_id: string;
    title: string;
    status: string;
    updated_at?: string;
    assigned_user_id?: string | null;
    due_at?: string | null;
    due_timezone?: string | null;
  }[];
};
